### ISSUE TITLE
所持品画像に輝石を含む画像を指定すると所持数にカウントされないことがある

### ISSUE THREAD

**Issue by kanata3249** [fgosc/fgosccalc#164]
所持品画像に輝石を含む画像を指定すると所持数にカウントされないことがある

オリジナルのpngファイルと、ブラウザで変換された後のjpegファイルを添付します
(変換後ファイルは、inputタグ(extra-image0)のvalueから取得したもの)

* オリジナルファイル(png)
![IMG_1592](https://user-images.githubusercontent.com/571779/116638535-81f3cf00-a9a1-11eb-9cd1-e1ff6f94445a.PNG)

* 変換後のファイル(jpeg)
![IMG_1592](https://user-images.githubusercontent.com/571779/116638549-8ae4a080-a9a1-11eb-924d-0939ad71155f.JPG)

**Comment by fgophi** [comment]
@kanata3249 
画像をいただき助かります
とりあえずお礼まで

**Comment by fgophi** [comment]
@kanata3249
スキル石の判別で認識させる座標がずれていたため、剣の輝石を弓の輝石と誤認識してしまっていたため、その後の処理で不整合が生じてしまっていました。

修正コード:
https://github.com/fgosc/fgosccalc/commit/6dd865385f7b50d0acd761aac755c292158d5d9a

## 修正前
```
剣の輝石部分の判別　(ID, 距離)のリスト
※6001 は剣の輝石、6002は弓の輝石
【PNG】
[(6001, 14.0), (6002, 20.0)]

【JPG】
[(6002, 16.0), (6001, 18.0)]
```

## 修正後
```
剣の輝石部分の判別　(ID, 距離)のリスト
※6001 は剣の輝石、6002は弓の輝石
【PNG】
[(6001, 4.0)]

【JPG】
[(6001, 10.0)]
```
