### ISSUE TITLE
fgosccalcで周回後の画像が読み込めませんでした。

### ISSUE THREAD

**Issue by viljo111** [fgosc/fgosccalc#175]
[画像.zip](https://github.com/fgosc/fgosccalc/files/7137423/default.zip)

上記周回後画像を読み込みしたところ認識がされませんでした。何か画像に不備がありますでしょうか。

**Comment by max747** [comment]
`IMG_0819.PNG` にわずかながら回転が入って傾いてしまっています。回転のない状態の画像でリトライしてください。
