### ISSUE TITLE
解析結果画面上で報告フォーマットを修正可能にする

### ISSUE THREAD

**Issue by max747** [fgosc/fgosccalc#46]
周回カウンタサイトと同じようなつくりで、報告フォーマットを解析結果画面上で修正にすることは可能に思う。
JS だけで完結する。

編集できると良いのは

- クエスト名
- 周回数
- 各素材の個数
- 素材をリストに入れるか入れないか

**Comment by fgophi** [comment]
**周回外の影響による自動計算**
各素材の個数に関しては

- 素材として使ってしまった数
- 別のクエストで入手してしまった数

を入れる欄を個別認識結果欄のあたりに設けて、自動合計した上で報告フォーマットの欄外にコメントとして出るのは需要があり、便利だと感じる機能だと思います

例

![image](https://user-images.githubusercontent.com/62515228/88124723-b8c5d900-cc08-11ea-8854-b02f2d7a31ba.png)
